spring.application.name=bankapi

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_db
spring.datasource.username=postgres
spring.datasource.password=admin123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Puerto
server.port=8080

# JWT
jwt.secret=claveSuperSecretaParaFirmarTokensJWT1234567890
jwt.expiration=86400000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Admin por defecto
admin.email=admin@bankapi.com
admin.password=admin1234